name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build the JAR file using Maven
      - name: Build with Maven
        run: mvn clean package
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=./.m2"

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: docker build -t mrsankofa/billtracker:latest .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push mrsankofa/billtracker:latest

# TODO: Try this process later
#      # Build the Docker image with version tag
#      - name: Build Docker image with tag
#        run: |
#          IMAGE_TAG=${GITHUB_SHA::7}
#          docker build -t <your-dockerhub-username>/<image-name>:${IMAGE_TAG} .
#          docker tag <your-dockerhub-username>/<image-name>:${IMAGE_TAG} <your-dockerhub-username>/<image-name>:latest
#
#      # Push the Docker image with version tag
#      - name: Push Docker image with tag
#        run: |
#          IMAGE_TAG=${GITHUB_SHA::7}
#          docker push <your-dockerhub-username>/<image-name>:${IMAGE_TAG}
#          docker push <your-dockerhub-username>/<image-name>:latest
